# Running all features
# default runs all features
<%
def_r = " -r features/support/env.rb -r features/step_definitions features "
def_f = " --format pretty "
def_t = " --tags ~@wip --tags ~@pending --tags ~@selenium"
def_opts = "#{def_r} #{def_f} #{def_t}"
%>

default: <%= def_opts %> 
wip: --tags @wip:2 --wip <%= def_r %> <%= def_f %>
pending: --tags @pending <%= def_r %> <%= def_f %>
textmate: --format=html <%= def_r %> <%= def_t %> 

